# These are supported funding model platforms

github: xinjie21
# patreon: # Replace with your Patreon
# ko_fi: # Replace with your Ko-fi
# buy_me_a_coffee: # Replace with your Buy Me a Coffee
# custom: ['https://your-custom-url.com']
